spring.application.name=proje

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/caretta_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:caretta}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:caretta_dev_sifresi}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRES_IN:7d}
